// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreateAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, name)
	var i Account
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const findAccountById = `-- name: FindAccountById :one
SELECT
    A.id,
    A.name,
    COALESCE(SUM(CASE WHEN t.type = 'income' THEN t.amount END), 0) AS total_income,
    COALESCE(SUM(CASE WHEN t.type = 'expense' THEN t.amount END), 0) AS total_expense,
    COALESCE(
        SUM(
            CASE
                WHEN T.type = 'income' THEN T.amount
                WHEN T.type = 'expense' THEN -T.amount
                ELSE 0
            END
        ),
        0
    ) AS total
FROM accounts A
LEFT JOIN transactions T ON T.account_id = A.id
WHERE A.id = $1
GROUP BY A.id, A.name
`

type FindAccountByIdRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	TotalIncome  interface{} `json:"totalIncome"`
	TotalExpense interface{} `json:"totalExpense"`
	Total        interface{} `json:"total"`
}

func (q *Queries) FindAccountById(ctx context.Context, id uuid.UUID) (FindAccountByIdRow, error) {
	row := q.db.QueryRow(ctx, findAccountById, id)
	var i FindAccountByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalIncome,
		&i.TotalExpense,
		&i.Total,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name FROM accounts ORDER BY name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
