// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Transaction struct {
	ID          uuid.UUID      `json:"id"`
	Amount      pgtype.Numeric `json:"amount"`
	Type        string         `json:"type"`
	AccountID   uuid.UUID      `json:"accountId"`
	Date        pgtype.Date    `json:"date"`
	Description pgtype.Text    `json:"description"`
}
