// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID     pgtype.UUID
	Name   string
	Amount pgtype.Numeric
}
