// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID     uuid.UUID      `json:"id"`
	Name   string         `json:"name"`
	Amount pgtype.Numeric `json:"amount"`
}
