// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package models

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (amount, type, account_id, date, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, amount, type, account_id, date, description
`

type CreateTransactionParams struct {
	Amount      pgtype.Numeric `json:"amount"`
	Type        string         `json:"type"`
	AccountID   uuid.UUID      `json:"accountId"`
	Date        pgtype.Date    `json:"date"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Amount,
		arg.Type,
		arg.AccountID,
		arg.Date,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Type,
		&i.AccountID,
		&i.Date,
		&i.Description,
	)
	return i, err
}

const findTransactionById = `-- name: FindTransactionById :one
SELECT id, amount, type, account_id, date, description FROM transactions WHERE id = $1
`

func (q *Queries) FindTransactionById(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, findTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Type,
		&i.AccountID,
		&i.Date,
		&i.Description,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, amount, type, account_id, date, description FROM transactions ORDER BY date DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.AccountID,
			&i.Date,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
